name: test deploy

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
      
